using System.Security.Claims;
using System.Text.Json;
using GameHub.Data;
using GameHub.Filters;
using GameHub.Helpers;
using GameHub.Models.Entities;
using GameHub.Models.Enums;
using GameHub.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace GameHub.Controllers
{
    [GameHubAuthorize(UserRole.SuperAdmin, UserRole.Admin, UserRole.BookingManager, UserRole.Receptionist, UserRole.FinanceManager, UserRole.Viewer)]
    [ValidateActiveUser]
    public class InvoicesController : Controller
    {
        private readonly ApplicationDbContext _db; private static readonly int[] PageSizes = [10, 25, 50];
        public InvoicesController(ApplicationDbContext db) => _db = db;

        public async Task<IActionResult> Index(string? search = null, InvoiceSourceType? sourceType = null, InvoiceStatus? status = null, int page = 1, int pageSize = 10, string sortBy = "newest")
        {
            if (!CanView()) return RedirectToAction("NotFound", "Error"); await SynchronizeOverdueAsync(); pageSize = PageSizes.Contains(pageSize) ? pageSize : 10;
            var query = _db.SalesInvoices.AsNoTracking().Include(x => x.Customer).Include(x => x.SalesOrder).Where(x => x.IsActive);
            if (!string.IsNullOrWhiteSpace(search)) { var t = search.Trim().ToLower(); query = query.Where(x => x.InvoiceNumber.ToLower().Contains(t) || (x.Subject ?? "").ToLower().Contains(t) || x.Customer.CustomerCode.ToLower().Contains(t) || (x.Customer.FirstName + " " + x.Customer.LastName).ToLower().Contains(t) || (x.SalesOrder != null && x.SalesOrder.SalesOrderNumber.ToLower().Contains(t))); }
            if (sourceType.HasValue) query = query.Where(x => x.SourceType == sourceType); if (status.HasValue) query = query.Where(x => x.Status == status);
            query = sortBy switch { "due" => query.OrderBy(x => x.DueDate), "total" => query.OrderByDescending(x => x.GrandTotal), _ => query.OrderByDescending(x => x.CreatedAt) };
            var total = await query.CountAsync(); var pages = Math.Max(1, (int)Math.Ceiling(total / (double)pageSize)); page = Math.Min(Math.Max(1, page), pages);
            var items = await query.Skip((page - 1) * pageSize).Take(pageSize).Select(x => new InvoiceListItemViewModel { Id = x.Id, InvoiceNumber = x.InvoiceNumber, Subject = x.Subject, RevisionNumber = x.RevisionNumber, SourceType = x.SourceType, SalesOrderNumber = x.SalesOrder == null ? null : x.SalesOrder.SalesOrderNumber, CustomerName = x.Customer.FirstName + " " + x.Customer.LastName, CustomerCode = x.Customer.CustomerCode, InvoiceDate = x.InvoiceDate, DueDate = x.DueDate, GrandTotal = x.GrandTotal, OutstandingAmount = x.OutstandingAmount, PaidAmount = x.PaidAmount, CurrencySymbol = x.CurrencySymbol, Status = x.Status }).ToListAsync();
            return View(new InvoiceIndexViewModel { Items = items, Search = search, SourceType = sourceType, Status = status, CurrentPage = page, PageSize = pageSize, TotalRecords = total, TotalPages = pages, SortBy = sortBy, CanCreate = CanCreate() });
        }

        [HttpGet("Invoices/CreateDirect")] public async Task<IActionResult> CreateDirect() => CanCreate() ? View("Form", await AddOptionsAsync(new InvoiceFormViewModel { Items = [new InvoiceItemViewModel { LineNumber = 1 }], Currency = (await Settings()).Currency, CurrencySymbol = (await Settings()).CurrencySymbol ?? "Rs" })) : RedirectToAction("NotFound", "Error");

        [HttpGet("Invoices/CreateFromSalesOrder/{salesOrderId:int}")]
        public async Task<IActionResult> CreateFromSalesOrder(int salesOrderId)
        {
            if (!CanCreate()) return RedirectToAction("NotFound", "Error"); var order = await ValidOrderAsync(salesOrderId); if (order == null) { TempData.SetToast("warning", "Invoice Blocked", "Only an active, approved Ready for Invoice sales order can be invoiced."); return RedirectToAction("Details", "SalesOrders", new { id = salesOrderId }); }
            return View("Form", await AddOptionsAsync(Map(order)));
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(InvoiceFormViewModel model, string? submitAction)
        {
            if (!CanCreate()) return RedirectToAction("NotFound", "Error"); Normalize(model); if (!await ValidateAsync(model)) return View("Form", await AddOptionsAsync(model));
            var order = model.SalesOrderId.HasValue ? await ValidOrderAsync(model.SalesOrderId.Value) : null; if (model.SalesOrderId.HasValue && order == null) { ModelState.AddModelError("", "Source sales order is no longer eligible for invoicing."); return View("Form", await AddOptionsAsync(model)); }
            await using var tx = await _db.Database.BeginTransactionAsync(); var settings = await Settings(); var invoice = Build(model, await NextNumberAsync(settings.InvoicePrefix)); invoice.Status = submitAction == "submit" ? InvoiceStatus.SubmittedForApproval : InvoiceStatus.Draft; invoice.IsLocked = invoice.Status == InvoiceStatus.SubmittedForApproval; invoice.SubmittedAt = invoice.IsLocked ? DateTime.UtcNow : null; _db.SalesInvoices.Add(invoice); await _db.SaveChangesAsync();
            if (order != null) { order.InvoiceCreated = true; order.InvoiceId = invoice.Id; order.UpdatedAt = DateTime.UtcNow; }
            await Activity(invoice, ApprovalAction.Created, "Invoice created."); if (invoice.IsLocked) await Approval(invoice, ApprovalAction.Submitted, InvoiceStatus.Draft.ToString(), null, null, false); await _db.SaveChangesAsync(); await tx.CommitAsync(); TempData.SetToast("success", "Invoice Created", "Invoice draft was created successfully."); return RedirectToAction(nameof(Details), new { id = invoice.Id });
        }

        public async Task<IActionResult> Edit(int id) { var invoice = await Load(false).FirstOrDefaultAsync(x => x.Id == id && x.IsActive); if (invoice == null || !invoice.IsEditable || !CanCreate()) return RedirectToAction("NotFound", "Error"); return View("Form", await AddOptionsAsync(Map(invoice))); }
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, InvoiceFormViewModel model, string? submitAction)
        {
            var invoice = await Load(true).FirstOrDefaultAsync(x => x.Id == id && x.IsActive); if (invoice == null || !invoice.IsEditable || !CanCreate()) return RedirectToAction("NotFound", "Error"); Normalize(model); if (!await ValidateAsync(model)) return View("Form", await AddOptionsAsync(model));
            if (model.RowVersion != null) _db.Entry(invoice).Property(x => x.RowVersion).OriginalValue = model.RowVersion; Apply(model, invoice); _db.SalesInvoiceItems.RemoveRange(invoice.Items); invoice.Items.Clear(); AddItems(model, invoice); invoice.UpdatedAt = DateTime.UtcNow; invoice.UpdatedByUserId = UserId(); if (submitAction == "submit") { invoice.Status = InvoiceStatus.SubmittedForApproval; invoice.IsLocked = true; invoice.SubmittedAt = DateTime.UtcNow; await Approval(invoice, ApprovalAction.Submitted, InvoiceStatus.Draft.ToString(), null, null, false); }
            try { await _db.SaveChangesAsync(); } catch (DbUpdateConcurrencyException) { ModelState.AddModelError("", "This invoice changed in another session. Reload and try again."); return View("Form", await AddOptionsAsync(model)); } TempData.SetToast("success", "Invoice Updated", "Invoice changes were saved."); return RedirectToAction(nameof(Details), new { id });
        }

        public async Task<IActionResult> Details(int id) { await SynchronizeOverdueAsync(); var invoice = await Load(false).FirstOrDefaultAsync(x => x.Id == id && x.IsActive); if (invoice == null || !CanView()) return RedirectToAction("NotFound", "Error"); return View(new InvoiceDetailsViewModel { Invoice = invoice, CanEdit = CanCreate() && invoice.IsEditable, CanApprove = CanApprove(), ApprovalHistory = await _db.DocumentApprovals.AsNoTracking().Include(x => x.ActionByUser).Where(x => x.DocumentType == DocumentType.SalesInvoice && x.DocumentId == id).OrderBy(x => x.ActionAt).ToListAsync(), RevisionHistory = await _db.DocumentRevisions.AsNoTracking().Include(x => x.CreatedByUser).Where(x => x.DocumentType == DocumentType.SalesInvoice && x.DocumentId == id).OrderBy(x => x.RevisionNumber).ToListAsync() }); }
        public async Task<IActionResult> Preview(int id) { var invoice = await Load(false).FirstOrDefaultAsync(x => x.Id == id && x.IsActive); return invoice == null ? RedirectToAction("NotFound", "Error") : View(new InvoicePreviewViewModel { Invoice = invoice, Settings = await Settings() }); }

        [HttpPost, ValidateAntiForgeryToken] public Task<IActionResult> SubmitForApproval(int id, string? comments) => SubmitAsync(id, comments, false);
        [HttpPost, ValidateAntiForgeryToken] public Task<IActionResult> Resubmit(int id, string revisionReason) => SubmitAsync(id, revisionReason, true);
        [HttpPost, ValidateAntiForgeryToken] public Task<IActionResult> Approve(int id, string? comments) => ApproveAsync(id, comments);
        [HttpPost, ValidateAntiForgeryToken] public Task<IActionResult> Reject(int id, string rejectionReason) => RejectAsync(id, rejectionReason);
        [HttpPost, ValidateAntiForgeryToken] public Task<IActionResult> Issue(int id) => TransitionAsync(id, InvoiceStatus.Approved, InvoiceStatus.Issued, ApprovalAction.Confirmed, null, "Invoice issued.");
        [HttpPost, ValidateAntiForgeryToken] public Task<IActionResult> Cancel(int id, string reason) => EndAsync(id, false, reason);
        [HttpPost, ValidateAntiForgeryToken] public Task<IActionResult> Void(int id, string reason) => EndAsync(id, true, reason);

        private async Task<IActionResult> SubmitAsync(int id, string? reason, bool revision) { var i = await Load(true).FirstOrDefaultAsync(x => x.Id == id && x.IsActive); if (i == null || !i.IsEditable || !CanCreate()) return RedirectToAction("NotFound", "Error"); if (revision && string.IsNullOrWhiteSpace(reason)) { TempData.SetToast("warning", "Revision Notes Required", "Provide revision notes before resubmitting."); return RedirectToAction(nameof(Details), new { id }); } await using var tx = await _db.Database.BeginTransactionAsync(); if (revision) { _db.DocumentRevisions.Add(new DocumentRevision { DocumentType = DocumentType.SalesInvoice, DocumentId = i.Id, DocumentNumber = i.InvoiceNumber, RevisionNumber = i.RevisionNumber, SnapshotJson = JsonSerializer.Serialize(i), RevisionReason = reason!.Trim(), CreatedByUserId = UserId(), CreatedAt = DateTime.UtcNow }); i.RevisionNumber++; } var prev = i.Status.ToString(); i.Status = InvoiceStatus.SubmittedForApproval; i.IsLocked = true; i.SubmittedAt = DateTime.UtcNow; await Approval(i, revision ? ApprovalAction.Resubmitted : ApprovalAction.Submitted, prev, reason, null, false); await Activity(i, revision ? ApprovalAction.Resubmitted : ApprovalAction.Submitted, "Invoice submitted for approval."); await _db.SaveChangesAsync(); await tx.CommitAsync(); return RedirectToAction(nameof(Details), new { id }); }
        private async Task<IActionResult> ApproveAsync(int id, string? comments) { var i = await _db.SalesInvoices.FirstOrDefaultAsync(x => x.Id == id && x.IsActive); if (i == null || i.Status != InvoiceStatus.SubmittedForApproval || !CanApprove()) return RedirectToAction("NotFound", "Error"); if (i.CreatedByUserId == UserId() && !Super()) { TempData.SetToast("warning", "Approval Blocked", "You cannot approve your own invoice."); return RedirectToAction(nameof(Details), new { id }); } i.Status = InvoiceStatus.Approved; i.ApprovedAt = DateTime.UtcNow; i.ApprovedByUserId = UserId(); await Approval(i, ApprovalAction.Approved, InvoiceStatus.SubmittedForApproval.ToString(), comments, null, true); await Activity(i, ApprovalAction.Approved, "Invoice approved."); await _db.SaveChangesAsync(); return RedirectToAction(nameof(Details), new { id }); }
        private async Task<IActionResult> RejectAsync(int id, string reason) { var i = await _db.SalesInvoices.FirstOrDefaultAsync(x => x.Id == id && x.IsActive); if (i == null || i.Status != InvoiceStatus.SubmittedForApproval || !CanApprove() || string.IsNullOrWhiteSpace(reason)) return RedirectToAction(nameof(Details), new { id }); i.Status = InvoiceStatus.Rejected; i.IsLocked = false; i.RejectedAt = DateTime.UtcNow; i.RejectedByUserId = UserId(); i.RejectionReason = reason.Trim(); await Approval(i, ApprovalAction.Rejected, InvoiceStatus.SubmittedForApproval.ToString(), null, i.RejectionReason, true); await Activity(i, ApprovalAction.Rejected, $"Invoice rejected: {i.RejectionReason}"); await _db.SaveChangesAsync(); return RedirectToAction(nameof(Details), new { id }); }
        private async Task<IActionResult> TransitionAsync(int id, InvoiceStatus from, InvoiceStatus to, ApprovalAction action, Action<SalesInvoice>? edit, string message) { var i = await _db.SalesInvoices.FirstOrDefaultAsync(x => x.Id == id && x.IsActive); if (i == null || i.Status != from || !CanApprove()) return RedirectToAction("NotFound", "Error"); i.Status = to; i.IsLocked = true; if (to == InvoiceStatus.Issued) i.IssuedAt = DateTime.UtcNow; edit?.Invoke(i); await Approval(i, action, from.ToString(), null, null, true); await Activity(i, action, message); await _db.SaveChangesAsync(); TempData.SetToast("success", "Invoice Updated", message); return RedirectToAction(nameof(Details), new { id }); }
        private async Task<IActionResult> EndAsync(int id, bool voided, string reason) { var i = await _db.SalesInvoices.FirstOrDefaultAsync(x => x.Id == id && x.IsActive); if (i == null || string.IsNullOrWhiteSpace(reason) || !CanApprove() || (!voided && i.Status is not (InvoiceStatus.Draft or InvoiceStatus.Rejected)) || (voided && i.Status != InvoiceStatus.Issued)) return RedirectToAction("NotFound", "Error"); i.Status = voided ? InvoiceStatus.Void : InvoiceStatus.Cancelled; if (voided) { i.VoidedAt = DateTime.UtcNow; i.VoidReason = reason.Trim(); } else { i.CancelledAt = DateTime.UtcNow; i.CancellationReason = reason.Trim(); } i.IsActive = !voided; await Approval(i, ApprovalAction.Cancelled, "", reason, reason, true); await _db.SaveChangesAsync(); return RedirectToAction(nameof(Index)); }

        private IQueryable<SalesInvoice> Load(bool tracked) { var q = _db.SalesInvoices.Include(x => x.Customer).Include(x => x.SalesOrder).Include(x => x.SalesQuotation).Include(x => x.Opportunity).Include(x => x.AssignedToUser).Include(x => x.Items).ThenInclude(x => x.Sport).Include(x => x.Items).ThenInclude(x => x.Facility).Include(x => x.Items).ThenInclude(x => x.Court).AsQueryable(); return tracked ? q : q.AsNoTracking(); }
        private async Task<SalesOrder?> ValidOrderAsync(int id) => await _db.SalesOrders.Include(x => x.Customer).Include(x => x.SalesQuotation).Include(x => x.Items).FirstOrDefaultAsync(x => x.Id == id && x.IsActive && x.Status == SalesOrderStatus.ReadyForInvoice && x.ApprovedAt != null && !x.InvoiceCreated && x.Customer.IsActive && !x.Customer.IsBlacklisted && x.Items.Any());
        private async Task<bool> ValidateAsync(InvoiceFormViewModel m) { var c = await _db.Customers.AsNoTracking().FirstOrDefaultAsync(x => x.Id == m.CustomerId); if (c == null || !c.IsActive || c.IsBlacklisted) ModelState.AddModelError(nameof(m.CustomerId), "Select an active, non-blacklisted customer."); if (m.DueDate < m.InvoiceDate) ModelState.AddModelError(nameof(m.DueDate), "Due date cannot be before invoice date."); if (!m.Items.Any(x => !string.IsNullOrWhiteSpace(x.Description))) ModelState.AddModelError("", "At least one item is required."); foreach (var x in m.Items.Where(x => !string.IsNullOrWhiteSpace(x.Description))) { if (x.Quantity <= 0 || x.UnitPrice < 0 || x.DiscountPercentage is < 0 or > 100 || x.TaxPercentage is < 0 or > 100 || (x.EndTime.HasValue && x.StartTime.HasValue && x.EndTime <= x.StartTime)) ModelState.AddModelError("", "Review item quantities, prices, percentages, and time range."); } return ModelState.IsValid; }
        private SalesInvoice Build(InvoiceFormViewModel m, string number) { var i = new SalesInvoice { InvoiceNumber = number, SourceType = m.SalesOrderId.HasValue ? InvoiceSourceType.SalesOrder : InvoiceSourceType.Direct, SalesOrderId = m.SalesOrderId, SalesQuotationId = m.SalesQuotationId, CustomerId = m.CustomerId, OpportunityId = m.OpportunityId, AssignedToUserId = m.AssignedToUserId, InvoiceDate = m.InvoiceDate, DueDate = m.DueDate, Subject = m.Subject, CustomerPurchaseOrderNumber = m.CustomerPurchaseOrderNumber, CustomerReference = m.CustomerReference, BillingAddress = m.BillingAddress, PaymentTerms = m.PaymentTerms, TermsAndConditions = m.TermsAndConditions, CustomerNotes = m.CustomerNotes, InternalNotes = m.InternalNotes, Currency = m.Currency, CurrencySymbol = m.CurrencySymbol, CreatedByUserId = UserId(), CreatedAt = DateTime.UtcNow }; Apply(m, i); AddItems(m, i); return i; }
        private void Apply(InvoiceFormViewModel m, SalesInvoice i) { i.InvoiceDate=m.InvoiceDate;i.DueDate=m.DueDate;i.AssignedToUserId=m.AssignedToUserId;i.Subject=m.Subject?.Trim();i.CustomerPurchaseOrderNumber=m.CustomerPurchaseOrderNumber?.Trim();i.CustomerReference=m.CustomerReference?.Trim();i.BillingAddress=m.BillingAddress?.Trim();i.PaymentTerms=m.PaymentTerms?.Trim();i.TermsAndConditions=m.TermsAndConditions?.Trim();i.CustomerNotes=m.CustomerNotes?.Trim();i.InternalNotes=m.InternalNotes?.Trim();i.AdjustmentAmount=m.AdjustmentAmount; }
        private void AddItems(InvoiceFormViewModel m, SalesInvoice invoice) { int n=1; decimal sub=0,discount=0,tax=0; foreach(var x in m.Items.Where(x=>!string.IsNullOrWhiteSpace(x.Description))) { var ls=Math.Round(x.Quantity*x.UnitPrice,2);var d=Math.Round(ls*x.DiscountPercentage/100m,2);var t=Math.Round((ls-d)*x.TaxPercentage/100m,2); invoice.Items.Add(new SalesInvoiceItem { LineNumber=n,DisplayOrder=n++,ItemType=x.ItemType,Description=x.Description.Trim(),Quantity=x.Quantity,UnitOfMeasure=x.UnitOfMeasure.Trim(),UnitPrice=x.UnitPrice,DiscountPercentage=x.DiscountPercentage,DiscountAmount=d,TaxPercentage=x.TaxPercentage,TaxAmount=t,LineSubtotal=ls,LineTotal=ls-d+t,ServiceDate=x.ServiceDate,StartTime=x.StartTime,EndTime=x.EndTime,CreatedAt=DateTime.UtcNow });sub+=ls;discount+=d;tax+=t; } invoice.Subtotal=sub;invoice.DiscountTotal=discount;invoice.TaxTotal=tax;invoice.GrandTotal=Math.Max(0,sub-discount+tax+invoice.AdjustmentAmount);invoice.OutstandingAmount=invoice.GrandTotal-invoice.PaidAmount; }
        private InvoiceFormViewModel Map(SalesOrder o) => new() { SalesOrderId=o.Id,SalesQuotationId=o.SalesQuotationId,CustomerId=o.CustomerId,OpportunityId=o.OpportunityId,AssignedToUserId=o.AssignedToUserId,SourceType=InvoiceSourceType.SalesOrder,SourceLabel=o.SalesOrderNumber,InvoiceDate=DateOnly.FromDateTime(DateTime.UtcNow),DueDate=DateOnly.FromDateTime(DateTime.UtcNow.AddDays(7)),Subject=o.Subject,CustomerPurchaseOrderNumber=o.CustomerPurchaseOrderNumber,CustomerReference=o.CustomerReference,TermsAndConditions=o.TermsAndConditions,CustomerNotes=o.CustomerNotes,InternalNotes=o.InternalNotes,Currency=o.Currency,CurrencySymbol=o.CurrencySymbol,Items=o.Items.Select(x=>new InvoiceItemViewModel { LineNumber=x.LineNumber,ItemType=x.ItemType,Description=x.Description,Quantity=x.Quantity,UnitOfMeasure=x.UnitOfMeasure,UnitPrice=x.UnitPrice,DiscountPercentage=x.DiscountPercentage,TaxPercentage=x.TaxPercentage,ServiceDate=x.ServiceDate,StartTime=x.StartTime,EndTime=x.EndTime }).ToList() };
        private InvoiceFormViewModel Map(SalesInvoice i) => new() { Id=i.Id,SalesOrderId=i.SalesOrderId,SalesQuotationId=i.SalesQuotationId,CustomerId=i.CustomerId,OpportunityId=i.OpportunityId,AssignedToUserId=i.AssignedToUserId,InvoiceDate=i.InvoiceDate,DueDate=i.DueDate,SourceType=i.SourceType,SourceLabel=i.SalesOrder?.SalesOrderNumber,Subject=i.Subject,CustomerPurchaseOrderNumber=i.CustomerPurchaseOrderNumber,CustomerReference=i.CustomerReference,BillingAddress=i.BillingAddress,PaymentTerms=i.PaymentTerms ?? "",TermsAndConditions=i.TermsAndConditions,CustomerNotes=i.CustomerNotes,InternalNotes=i.InternalNotes,AdjustmentAmount=i.AdjustmentAmount,Currency=i.Currency,CurrencySymbol=i.CurrencySymbol,RowVersion=i.RowVersion,IsEditable=i.IsEditable,Items=i.Items.OrderBy(x=>x.LineNumber).Select(x=>new InvoiceItemViewModel { LineNumber=x.LineNumber,ItemType=x.ItemType,Description=x.Description,Quantity=x.Quantity,UnitOfMeasure=x.UnitOfMeasure,UnitPrice=x.UnitPrice,DiscountPercentage=x.DiscountPercentage,TaxPercentage=x.TaxPercentage,ServiceDate=x.ServiceDate,StartTime=x.StartTime,EndTime=x.EndTime }).ToList() };
        private async Task<InvoiceFormViewModel> AddOptionsAsync(InvoiceFormViewModel m) { m.CustomerOptions=await _db.Customers.AsNoTracking().Where(x=>x.IsActive&&!x.IsBlacklisted).Select(x=>new SelectListItem(x.FirstName+" "+x.LastName+" - "+x.CustomerCode,x.Id.ToString(),x.Id==m.CustomerId)).ToListAsync();m.UserOptions=await _db.Users.AsNoTracking().Where(x=>x.IsActive).Select(x=>new SelectListItem(x.FirstName+" "+x.LastName,x.Id.ToString(),x.Id==m.AssignedToUserId)).ToListAsync();m.OpportunityOptions=await _db.Opportunities.AsNoTracking().Where(x=>x.IsActive).Select(x=>new SelectListItem(x.OpportunityNumber+" - "+x.Name,x.Id.ToString(),x.Id==m.OpportunityId)).ToListAsync();return m; }
        private async Task<string> NextNumberAsync(string prefix) { prefix=string.IsNullOrWhiteSpace(prefix)?"INV":prefix.Trim().ToUpperInvariant();var last=await _db.SalesInvoices.Where(x=>x.InvoiceNumber.StartsWith(prefix+"-")).OrderByDescending(x=>x.InvoiceNumber).Select(x=>x.InvoiceNumber).FirstOrDefaultAsync();return $"{prefix}-{(last!=null&&int.TryParse(last.Split('-').Last(),out var n)?n+1:1):000000}"; }
        private async Task<SystemSettings> Settings() => await _db.SystemSettings.AsNoTracking().FirstOrDefaultAsync() ?? new SystemSettings { ArenaName="GameHub Arena",Currency="PKR",CurrencySymbol="Rs",InvoicePrefix="INV" };
        private async Task Approval(SalesInvoice i, ApprovalAction a,string previous,string? comment,string? reason,bool final) { _db.DocumentApprovals.Add(new DocumentApproval { DocumentType=DocumentType.SalesInvoice,DocumentId=i.Id,DocumentNumber=i.InvoiceNumber,RevisionNumber=i.RevisionNumber,Action=a,PreviousStatus=previous,NewStatus=i.Status.ToString(),SubmittedByUserId=UserId(),ActionByUserId=UserId(),SubmittedAt=a is ApprovalAction.Submitted or ApprovalAction.Resubmitted?DateTime.UtcNow:null,ActionAt=DateTime.UtcNow,Comments=comment,RejectionReason=reason,FinancialTotal=i.GrandTotal,Currency=i.Currency,IsFinal=final,IpAddress=HttpContext.Connection.RemoteIpAddress?.ToString(),CreatedAt=DateTime.UtcNow }); await Task.CompletedTask; }
        private async Task Activity(SalesInvoice i, ApprovalAction type,string text) { _db.DocumentActivities.Add(new DocumentActivity { DocumentType=DocumentType.SalesInvoice,DocumentId=i.Id,ActivityType=type,Description=text,PerformedByUserId=UserId(),PerformedAt=DateTime.UtcNow });await Task.CompletedTask; }
        private async Task SynchronizeOverdueAsync() { var today=DateOnly.FromDateTime(DateTime.UtcNow);var list=await _db.SalesInvoices.Where(x=>x.IsActive&&(x.Status==InvoiceStatus.Issued||x.Status==InvoiceStatus.PartiallyPaid)&&x.DueDate<today&&x.OutstandingAmount>0).ToListAsync(); foreach(var x in list)x.Status=InvoiceStatus.Overdue; if(list.Any())await _db.SaveChangesAsync(); }
        private static void Normalize(InvoiceFormViewModel m) { m.Subject=m.Subject?.Trim();m.PaymentTerms=m.PaymentTerms?.Trim()??"";foreach(var x in m.Items){x.Description=x.Description?.Trim()??"";x.UnitOfMeasure=string.IsNullOrWhiteSpace(x.UnitOfMeasure)?"Unit":x.UnitOfMeasure.Trim();} }
        private int UserId()=>int.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier),out var id)?id:0; private bool CanView()=>RolePermissions.CanAccessModule(User,"Sales"); private bool CanCreate()=>RolePermissions.TryGetCurrentRole(User,out var r)&&r is UserRole.SuperAdmin or UserRole.Admin or UserRole.BookingManager or UserRole.Receptionist; private bool CanApprove()=>RolePermissions.TryGetCurrentRole(User,out var r)&&r is UserRole.SuperAdmin or UserRole.Admin or UserRole.FinanceManager; private bool Super()=>RolePermissions.TryGetCurrentRole(User,out var r)&&r==UserRole.SuperAdmin;
    }
}
